src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: QuestionRepository::class)]
class Question
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private ? string $name;

    #[ORM\Column(type: 'string', length: 100, unique: true)]
    private $slug;

    #[ORM\Column(type: 'text')]
    private $question;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $askedAt;

    #[ORM\Column(type: 'integer')]
    private $votes = 0;

    #[ORM\OneToMany(mappedBy: 'question', targetEntity: Answer::class, fetch: 'EXTRA_LAZY')]
    #[ORM\OrderBy(["createdAt" => "DESC"])]
    private $answers;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAskedAt(): ?\DateTimeImmutable
    {
        return $this->askedAt;
    }

    public function setAskedAt(?\DateTimeImmutable $askedAt): self
    {
        $this->askedAt = $askedAt;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >=0 ? '+' : '-';
        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function upVote(): self
    {
        $this->votes++;
        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;
        return $this;
    }

    /**
     * @return Collection<int, Answer>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function getApprovedAnswers(): Collection
    {
        return $this->answers->filter(function(Answer $answer){
            return $answer->isApproved();
        });
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }
}

src/Controller/QuestionController.php
<?php

namespace App\Controller;


use App\Entity\Question;
use App\Repository\QuestionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sentry\State\HubInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class QuestionController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(QuestionRepository $questionRepository): Response
    {
        $questions = $questionRepository->findAllAskedOrderdByNewest();

        return $this->render('question/homepage.html.twig', [
            'questions' => $questions
        ]);
    }

    #[Route('/questions/new', name: 'app_question_new')]
    public function new(EntityManagerInterface $entityManager)
    {
        return new Response('TODO questions/new page');
    }

    #[Route('/questions/{slug}', name: 'app_question_show')]
    public function show(Question $question)
    {


        return $this->render('question/show.html.twig', [
            'question' => $question,
        ]);
    }

    #[Route('/questions/{slug}/vote', name: 'app_question_vote', methods: "POST")]
    public function questionVote(Question $question, Request $request, EntityManagerInterface $em)
    {
        $direction  = $request->request->get('direction');
        if ($direction === 'up') {
            $question->upVote();
        } elseif ($direction === 'down') {
            $question->downVote();
        }

        $em->flush();

        return $this->redirectToRoute('app_question_show', [
            'slug' => $question->getSlug()
        ]);

    }


}

templates/question/homepage.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main>
        <div class="jumbotron-img p-5 mb-5">
            <div class="container">
                <h1 class="display-4">Your Questions Answered</h1>
                <p class="lead">And even answers for those questions you didn't think to ask!</p>
            </div>
        </div>
        <div class="container">
            <div class="row mb-3">
                <div class="col">
                    <button class="btn btn-question">Ask a Question</button>
                </div>
            </div>
            <div class="row">
                {% for question in questions %}
                <div class="col-12">
                    <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                        <div class="q-container p-4">
                            <div class="row">
                                <div class="col-2 text-center">
                                    <img src="{{ asset('build/images/tisha.png') }}" width="100" height="100">
                                    <div class="mt-3">
                                        <small>
                                            {% if question.askedAt %}
                                                Asked <br>
                                                {{ question.askedAt|ago }}
                                            {% else %}
                                                (unpublished)
                                            {% endif %}
                                        </small>
                                    </div>
                                    <div class="d-block mt-3 vote-arrows">
                                        <a class="vote-up" href="#"><i class="fa fa-arrow-circle-o-up"></i></a>
                                        <a class="vote-down" href="#"><i class="fa fa-arrow-circle-o-down"></i></a>
                                        <span>+ <span class="js-vote-total">6</span></span>
                                    </div>
                                </div>

                                <div class="col">
                                    <a class="q-title" href="{{ path('app_question_show', { slug: question.slug }) }}"><h2>
                                        {{ question.name }}</h2></a>
                                    <div class="q-display p-3">
                                        <i class="fa fa-quote-left mr-3"></i>
                                        <p class="d-inline">{{ question.question|markdown_to_html }}</p>
                                        <p class="pt-4"><strong>--Tisha</strong></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="answer-link" href="{{ path('app_question_show', { slug:  question.slug  }) }}" style="color: #fff;">
                            <p class="q-display-response text-center p-3">
                                <i class="fa fa-magic magic-wand"></i> {{ question.approvedAnswers|length}} answers
                            </p>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}

templates/question/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Question: {{ question.name }}{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="my-4">Question:</h2>
            <div style="box-shadow: 2px 3px 9px 4px rgba(0,0,0,0.04);">
                <div class="q-container-show p-4">
                    <div class="row">
                        <div class="col-2 text-center">
                            <img src="{{ asset('build/images/tisha.png') }}" width="100" height="100">
                        </div>
                        <div class="mt-3">
                            <small>
                                {% if question.askedAt %}
                                    Asked <br>
                                    {{ question.askedAt|ago }}
                                {% else %}
                                    (unpublished)
                                {% endif %}
                            </small>
                        </div>

                        <div class="col">
                            <h1 class="q-title-show">{{ question.name }}</h1>
                            <div class="q-display p-3">
                                <i class="fa fa-quote-left mr-3"></i>
                                <p class="d-inline">{{ question.question|markdown_to_html }}</p>
                                <p class="pt-4"><strong>--Tisha</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="d-flex justify-content-between my-4">
        <h2 class="">Answers <span style="font-size:1.2rem;">({{ question.approvedAnswers|length }})</span></h2>
        <button class="btn btn-sm btn-secondary">Submit an Answer</button>
    </div>

    <ul class="list-unstyled">
        {% for answer in question.approvedAnswers %}
            <li class="mb-4">
                <div class="row justify-content-center">
                    <div class="col-1 pt-2">
                        <img alt="" src="{{ asset('build/images/tisha.png') }}" width="50" height="50">
                    </div>
                    <div class="col-9 pt-2">
                        {{ answer.content|markdown_to_html }}
                        <p>-- {{ answer.username }}</p>
                    </div>
                    <div class="col-2 text-center">
                        <small>{{ question.createdAt|ago }}</small>
                        <div class="vote-arrows"
                                {{ stimulus_controller('answer-vote', {
                                    url: path('answer_vote', {
                                        id: answer.id
                                    })
                                }) }}
                        >
                            <button
                                    class="vote-up btn btn-lg btn-link px-0"
                                    name="direction"
                                    value="up"
                                    {{ stimulus_action('answer-vote', 'clickVote') }}
                            ><i class="fa fa-arrow-circle-o-up"></i></button>
                            <button
                                    class="vote-down btn btn-lg btn-link px-0"
                                    name="direction"
                                    value="down"
                                    {{ stimulus_action('answer-vote', 'clickVote') }}
                            ><i class="fa fa-arrow-circle-o-down"></i></button>
                            <span><span {{ stimulus_target('answer-vote', 'voteTotal') }}>{{ answer.votes }}</span></span>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>

</div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
{#    {{ encore_entry_script_tags('question') }}#}

{% endblock %}